# Generated by Django 3.1 on 2021-02-17 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Featureversion', '0001_initial'),
        ('Layer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerDiffFeatureversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification', models.TextField()),
                ('featureversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Featureversion.featureversion')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Layer.layer')),
            ],
            options={
                'db_table': 'layer_diff_featureversion',
                'managed': True,
                'unique_together': {('layer', 'featureversion')},
            },
        ),
    ]
