# Generated by Django 3.1 on 2021-02-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaMigrations',
            fields=[
                ('version', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'schema_migrations',
                'managed': True,
            },
        ),
    ]
