# Generated by Django 3.1 on 2021-02-17 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Namespace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Namespace.namespace')),
            ],
            options={
                'db_table': 'feature',
                'managed': True,
                'unique_together': {('namespace', 'name')},
            },
        ),
    ]
